// <auto-generated />
using Mango.Services.CouponAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mango.Services.CouponAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mango.Services.CouponAPI.Models.Coupon", b =>
                {
                    b.Property<int>("CouponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CouponId"));

                    b.Property<string>("CouponCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<double>("DiscountAmount")
                        .HasColumnType("float");

                    b.Property<int>("MinAmount")
                        .HasColumnType("int");

                    b.HasKey("CouponId");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            CouponId = 1,
                            CouponCode = "CODE1",
                            DiscountAmount = 10.0,
                            MinAmount = 10
                        },
                        new
                        {
                            CouponId = 2,
                            CouponCode = "CODE2",
                            DiscountAmount = 20.0,
                            MinAmount = 20
                        },
                        new
                        {
                            CouponId = 3,
                            CouponCode = "CODE3",
                            DiscountAmount = 30.0,
                            MinAmount = 30
                        },
                        new
                        {
                            CouponId = 4,
                            CouponCode = "CODE4",
                            DiscountAmount = 40.0,
                            MinAmount = 40
                        },
                        new
                        {
                            CouponId = 5,
                            CouponCode = "CODE5",
                            DiscountAmount = 50.0,
                            MinAmount = 50
                        },
                        new
                        {
                            CouponId = 6,
                            CouponCode = "CODE6",
                            DiscountAmount = 60.0,
                            MinAmount = 60
                        },
                        new
                        {
                            CouponId = 7,
                            CouponCode = "CODE7",
                            DiscountAmount = 70.0,
                            MinAmount = 70
                        },
                        new
                        {
                            CouponId = 8,
                            CouponCode = "CODE8",
                            DiscountAmount = 80.0,
                            MinAmount = 80
                        },
                        new
                        {
                            CouponId = 9,
                            CouponCode = "CODE9",
                            DiscountAmount = 90.0,
                            MinAmount = 90
                        },
                        new
                        {
                            CouponId = 10,
                            CouponCode = "CODE10",
                            DiscountAmount = 100.0,
                            MinAmount = 100
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
